#! /bin/sh

if [ -n "$BASH_SOURCE" ]; then
    THIS_SCRIPT=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    THIS_SCRIPT=$0
else
    THIS_SCRIPT="$(pwd)/oe-init-build-env"
    if [ ! -e "$THIS_SCRIPT" ]; then
        echo "Error: $THIS_SCRIPT doesn't exist!" >&2
        echo "Please run this script in oe-init-build-env's directory." >&2
        exit 1
    fi
fi

export TEMPLATECONF="$(realpath $(dirname $THIS_SCRIPT)/meta-doom-demo/conf/templates/doom-demo)"

if [ -n "$1" ]; then
    BUILDDIR=$(realpath "$1")
else
    BUILDDIR=$(realpath $(dirname $THIS_SCRIPT))/build
fi

cd $(dirname $THIS_SCRIPT)/core
. oe-init-build-env "$BUILDDIR"

export BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} BUILD_DEVICE"
