name: parse-devices
run-name: "Parse Devices"
on:
  pull_request: {}
  push:
    branches:
      - main
      - gh-actions
jobs:
  parse:
    name: Parse Device
    runs-on: Ubuntu-22.04
    strategy:
      matrix:
        device:
          - le-potato
          - odroid-c4
          - odroid-h3
          - qemu
          - raspberrypi3
          - raspberrypi4
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 0

      - name: Update apt
        run: sudo apt update -y

      - name: Install dependencies
        run: |
          sudo apt install -y gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev python3-subunit mesa-common-dev zstd liblz4-tool

      - name: Parse config for ${{ matrix.device }}
        run: |
          . init-build-env
          export BUILD_DEVICE=${{ matrix.device }}
          bitbake -p core-image-doom
